tuple1 = (0, 1, 2, 3, 2, 31, 1, 3, 2, 3)
res = tuple1.count(3)
print(res)
res = tuple1.index(3)
print(res)
# res = tuple1.index(311) # ValueError: tuple.index(x): x not in tuple
res = tuple1.index(31, 1, 6)
print(res)
res = len(tuple1)
print(res)
res = tuple1.count(3)
print('Count of 3 in tuple1 is:', res)